### ISSUE TITLE
Gromacs demo: coordination_url is not propagated via session to plugin_overlay_provisioner_bigjob_pilot.py

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#15]
Execution fails with the following:

Traceback (most recent call last):
  File "gromacs_demo.py", line 95, in <module>
    troy.execute_workload(workload_id, planner, overlay_mgr, workload_mgr, strategy='basic')
  File "/Users/matteo/Virtualenvs/TROY/lib/python2.7/site-packages/troy/strategy.py", line 34, in execute_workload
    strategy.execute (workload_id, planner, overlay_mgr, workload_mgr)
  File "/Users/matteo/Virtualenvs/TROY/lib/python2.7/site-packages/pilot/filemanagement/../../troy/plugins/strategy/plugin_strategy_basic.py", line 57, in execute
    overlay_id = overlay_mgr.create_overlay (overlay_descr)
  File "/Users/matteo/Virtualenvs/TROY/lib/python2.7/site-packages/troy/overlay/overlay_manager.py", line 227, in create_overlay
    self._init_plugins  (workload_mgr=workload_mgr)
  File "/Users/matteo/Virtualenvs/TROY/lib/python2.7/site-packages/troy/overlay/overlay_manager.py", line 132, in _init_plugins
    self._provisioner.init_plugin (self._session)
  File "/Users/matteo/Virtualenvs/TROY/lib/python2.7/site-packages/troy/plugin_base.py", line 34, in init_plugin
    self.init ()
  File "/Users/matteo/Virtualenvs/TROY/lib/python2.7/site-packages/pilot/filemanagement/../../troy/plugins/overlay_provisioner/plugin_overlay_provisioner_bigjob_pilot.py", line 60, in init
    raise RuntimeError ("Cannot use bigjob_pilot backend - no COORDINATION_URL -- see debug log for details")
RuntimeError: Cannot use bigjob_pilot backend - no COORDINATION_URL -- see debug log for details

**Comment by andre-merzky** [comment]
Error message is improved.  Coord URL is considered part of the static config settings, and is in troy.cfg.  That is documented -- env variable is still accepted as backup, for backward compatibility.
