### ISSUE TITLE
Paramiko dependency should be added to setup

### ISSUE THREAD

**Issue by ashleyz** [radical-cybertools/radical.owms#29]
With a fresh SAGA-Python/TROY install (devel for both) installed with `pip install .` the following warning appears:

```
CRITICAL:root:Bundle Agent depends on paramiko package installation.
```

This warning goes away once you install Paramiko.

**Comment by ashleyz** [comment]
Seems redundant, actually to #12, though the error is different (throws planner error instead of strategy)

```
Traceback (most recent call last):
  File "examples/phase1_demo_1.py", line 54, in <module>
    planner.expand_workload(workload_id)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/utils/time_it.py", line 10, in timed
    result = method (*args, **kwargs)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/planner/planner.py", line 124, in expand_workload
    self._init_plugins (workload)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/planner/planner.py", line 66, in _init_plugins
    self._planner    = self._plugin_mgr.load ('planner', self.plugins['planner'])
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/radical/utils/plugin_manager.py", line 253, in load
    raise LookupError ("No such plugin type %s" % ptype)
LookupError: No such plugin type planner
```

**Comment by andre-merzky** [comment]
Thanks Ashley.  This is in sync with Matteo's suggestion, I'll add that dependency.
