### ISSUE TITLE
Signature mismatch in devel phase 1 demo 3

### ISSUE THREAD

**Issue by ashleyz** [radical-cybertools/radical.owms#41]
Hello!
Apologies if this is redundant, as this was discussed yesterday morning, but with phase 1 demo 3 I get the following error:

```
Traceback (most recent call last):
  File "examples/phase1_demo_3.py", line 79, in <module>
    troy.execute_workload (workload_id, planner, overlay_mgr, workload_mgr, strategy='basic')
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/strategy.py", line 43, in execute_workload
    strategy.execute (workload_id, planner, overlay_mgr, workload_mgr)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/pilot/filemanagement/../../troy/plugins/strategy/plugin_strategy_basic.py", line 92
, in execute
    workload_mgr.stage_in_workload (partition_id)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/utils/time_it.py", line 10, in timed
    result = method (*args, **kwargs)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/workload/workload_manager.py", line 427, in stage_in_workload
    self._stager.stage_in_workload (workload)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/workload/data_stager.py", line 95, in stage_in_workload
    self._stage_in_task (workload.tasks[task_id])
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/workload/data_stager.py", line 102, in _stage_in_task
    self._stage_in_unit (task.units[unit_id])
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/workload/data_stager.py", line 149, in _stage_in_unit
    self._stage_in_file (one, pilot.resource, workdir, two)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/troy/workload/data_stager.py", line 199, in _stage_in_file
    tgt_dir.change_dir (os.path.dirname (tgt), saga.filesystem.CREATE_PARENTS)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/radical/utils/signatures.py", line 440, in takes_invocation_proxy
    raise_type_exception (method, pargs[0], i, arg)
  File "/home/ashley/troy-env/local/lib/python2.7/site-packages/radical/utils/signatures.py", line 390, in raise_type_exception
    raise TypeError (msg)
TypeError: 
Signature Mismatch
  in function        : _stage_in_file
  in file            : /home/ashley/troy-env/local/lib/python2.7/site-packages/troy/workload/data_stager.py +199
  on line            : tgt_dir.change_dir (os.path.dirname (tgt), saga.filesystem.CREATE_PARENTS)
  method             : change_dir
  argument           : #2
  has incorrect type : <type 'int'>
```

Feel free to close this if I'm missing something...  executed with devel saga-python/sinon/TROY...

**Comment by andre-merzky** [comment]
Troy at the moment wants saga-python's devel branch -- there was a bugfix on the change_dir signature which would explain this error...

**Comment by andre-merzky** [comment]
This has been resolved, and should not happen anymore.
