### ISSUE TITLE
Unclean shutdown of sagapilot

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.owms#77]
At the end of a troy run, in the logs I see the following:

```
2014:03:09 16:08:55 MainThread   troy.logger           : [INFO    ] all partition done (Done)
2014:03:09 16:08:55 MainThread   troy.logger           : [WARNING ] shutting down workload: wl.0001
2014:03:09 16:08:55 MainThread   troy.logger           : [WARNING ] shutting down overlay: ol.0001
2014:03:09 16:08:55 MainThread   troy.logger           : [INFO    ] cancel pilot    p.0001
2014:03:09 16:08:55 MainProcess:MainThread sagapilot.logger      : [INFO    ] Sent 'CANCEL' to pilots ['531c8ed3740a007afd2fb064'].
2014:03:09 16:08:56 MainThread   troy.logger           : [DEBUG   ] dumped timing to mongodb...

Exception in thread UMWThread-531c8ed3740a007afd2fb062 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/home/mturilli/Virtualenvs/AIMES-SC2014/local/lib/python2.7/site-packages/sagapilot/mpworker/unit_manager_worker.py", line 234, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

Does it mean that sagapilot does not exit cleanly?

**Comment by andre-merzky** [comment]
This seems to be a sagapilot error -- I'll created a ticket there...
